### ISSUE TITLE
北京超算，vasp6.3.0安装报错

### ISSUE THREAD

**Issue by hz-hz22** [hellozhaoming/FCP-vasp-ase#5]
错误信息为：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

  File "/public3/home/m6s001397/.conda/envs/ase/lib/python3.9/site-packages/ase/calculators/FCPelectrochem.py", line 50, in __init__

    FileIOCalculator.__init__(self)

  File "/public3/home/m6s001397/.conda/envs/ase/lib/python3.9/site-packages/ase/calculators/calculator.py", line 1107, in __init__

    profile = self._initialize_profile(command)

  File "/public3/home/m6s001397/.conda/envs/ase/lib/python3.9/site-packages/ase/calculators/calculator.py", line 1158, in _initialize_profile

    raise EnvironmentError(

ase.calculators.calculator.EnvironmentError: No configuration of FCP.  Missing section [FCP] in configuration
请问如何处理，十分感谢

**Comment by hellozhaoming** [comment]
非常抱歉，好久没有登陆，没看到消息。这是ase23.0版本需要定义config.ini引起的。只需要在~/.config/ase/config.ini文件里写入：
[FCP]
command =
pseudo_path =

**Comment by xnmao** [comment]
> 非常抱歉，好久没有登陆，没看到消息。这是ase23.0版本需要定义config.ini引起的。只需要在~/.config/ase/config.ini文件里写入： [FCP] command = pseudo_path =

你好，`~/.config/ase/config.ini`里面`command `和`pseudo_path`的具体内容应该填什么呢，有例子吗？

**Comment by Underbigbridge** [comment]
> > 非常抱歉，好久没有登陆，没看到消息。这是ase23.0版本需要定义config.ini引起的。只需要在~/.config/ase/config.ini文件里写入： [FCP] command = pseudo_path =
> 
> 你好，`~/.config/ase/config.ini`里面`command `和`pseudo_path`的具体内容应该填什么呢，有例子吗？

分别是你运行vasp的命令，pseudo potential 的路径
